// EndPoints

export const JUAN = 'http://localhost:51066/api';
export const CAMILO = 'http://localhost:56757/api';


// Categories constant

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const UNMOUNT_CATEGORY = 'UNMOUNT_CATEGORY';

// Courses constant
export const CREATE_COURSE = 'CREATE_COURSE';
export const FETCH_COURSES = 'FETCH_COURSES';
export const FETCH_COURSE = 'FETCH_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const EDIT_COURSE = 'EDIT_COURSE';
export const FETCH_COURSE_BY_CATEGORY = 'FETCH_COURSE_BY_CATEGORY';
export const FETCH_COURSES_BY_USERNAME = 'FETCH_COURSES_BY_USERNAME';
export const POST_COURSE = 'POST_COURSE';
export const COURSE_CAN_BE_POSTED = 'COURSE_CAN_BE_POSTED';
export const UNMOUNT_LOADING_COURSE = 'UNMOUNT_LOADING_COURSE';
export const UNMOUNT_DETAIL_COURSE = 'UNMOUNT_DETAIL_COURSE';
export const CREATING_COURSE = 'CREATING_COURSE';
export const EDITING_COURSE = 'EDITING_COURSE';

//current user
export const CURRENT_USER = 'Mr. Sample';


//error constant
export const UPDATE_ERROR_WITH_ACTION = 'UPDATE_ERROR_WITH_ACTION'
export const UPDATE_ERROR_UNMOUNT = 'UPDATE_ERROR_UNMOUNT'

// CourseContent constant

export const UNMOUNT_COURSE_CONTENT = 'UNMOUNT_COURSE_CONTENT';

// Subject constant

export const FETCH_SUBJECTS = 'FETCH_SUBJECTS';
export const FETCH_SUBJECT = 'FETCH_SUBJECT';
export const CREATE_SUBJECT = 'CREATE_SUBJECT';
export const EDIT_SUBJECT = 'EDIT_SUBJECT';
export const IS_EDITING_SUBJECT = 'IS_EDITING_SUBJECT';
export const IS_NOT_EDITING_SUBJECT = 'IS_NOT_EDITING_SUBJECT';
export const IS_CREATING_SUBJECT = 'IS_CREATING_SUBJECT';
export const IS_NOT_CREATING_SUBJECT = 'IS_NOT_CREATING_SUBJECT';
export const UNMOUNT_CREATE_SUBJECT_FORM = 'UNMOUNT_CREATE_SUBJECT_FORM';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const UNMOUNT_SUBJECTS_LOADING = 'UNMOUNT_SUBJECTS_LOADING';

// Content constant

export const FETCH_CONTENTS = 'FETCH_CONTENTS';
export const FETCH_CONTENT = 'FETCH_CONTENT';
export const CREATE_CONTENT = 'CREATE_CONTENT';
export const EDIT_CONTENT = 'EDIT_CONTENT';
export const IS_CREATING_CONTENT = 'IS_CREATING_CONTENT';
export const IS_NOT_CREATING_CONTENT = 'IS_NOT_CREATING_CONTENT';
export const IS_EDITING_CONTENT = 'IS_EDITING_CONTENT';
export const IS_NOT_EDITING_CONTENT = 'IS_NOT_EDITING_CONTENT';
export const DELETE_CONTENT = 'DELETE_CONTENT';
export const UNMOUNT_CONTENT = 'UNMOUNT_CONTENT';
export const FETCH_LAST_CONTENT_DESCENDING = 'FETCH_LAST_CONTENT_DESCENDING'

//success
export const UPDATE_SUCCESS_UNMOUNT = 'UPDATE_SUCCESS_UNMOUNT'

//Unmount  CanBePosted
export const UNMOUNT_CAN_BE_POSTED = 'UNMOUNT_CAN_BE_POSTED'


//Question
export const FETCH_QUESTIONS_BY_COURSE_ID = 'FETCH_QUESTIONS_BY_COURSE_ID'
export const IS_CREATING_QUESTION = 'IS_CREATING_QUESTION';
export const IS_NOT_CREATING_QUESTION = 'IS_NOT_CREATING_QUESTION';
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const IS_EDITING_QUESTION = 'IS_EDITING_QUESTION';
export const IS_NOT_EDITING_QUESTION = 'IS_NOT_EDITING_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const UNMOUNT_QUESTION = 'UNMOUNT_QUESTION';
export const UNMOUNT_CREATE_QUESTION_FORM = 'UNMOUNT_CREATE_QUESTION_FORM';
export const FETCH_QUESTION = 'FETCH_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const UNMOUNT_QUESTIONS_LOADING = 'UNMOUNT_QUESTIONS_LOADING';

// UserCourse
export const FETCH_USERCOURSES_BY_USERNAME = 'FETCH_USERCOURSES_BY_USERNAME';
export const CREATE_USERCOURSE_BY_USERNAME = 'CREATE_USERCOURSE_BY_USERNAME';
export const FETCH_USERCOURSE = 'FETCH_USERCOURSE';
export const UPDATE_RATING_USERCOURSE = 'UPDATE_RATING_USERCOURSE';
export const UNMOUNT_LOADING_USERCOURSE = 'UNMOUNT_LOADING_USERCOURSE';


//Options
export const FETCH_OPTIONS_BY_QUESTION_ID = 'FETCH_OPTIONS_BY_QUESTION_ID'
export const CREATE_OPTIONS = 'CREATE_OPTIONS'
export const EDIT_OPTIONS = 'EDIT_OPTIONS'
export const DELETE_OPTIONS = 'DELETE_OPTIONS'
export const SUCCESS_UNMOUNT_OPTIONS = 'UPDATE_SUCCESS_UNMOUNT'
export const FETCH_OPTIONS = 'FETCH_OPTIONS'


//UserContent
export const FETCH_USER_CONTENTS_BY_USERNAME = 'FETCH_USER_CONTENTS_BY_USERNAME'


//CurrenteContentPlayer
export const CURRENT_CONTENT_PLAYER= 'CURRENT_CONTENT_PLAYER'
export const UNMOUNT_CONTENT_PLAYER = 'UNMOUNT_CONTENT_PLAYER'

//Exam
export const FETCH_QUESTIONS_EXAM = 'FETCH_QUESTIONS_EXAM'
export const VALIDATE_ANSWERS_EXAM = 'VALIDATE_ANSWERS_EXAM'
export const UPDATE_USER_COURSE_CORRECTANSWERS = 'UPDATE_USER_COURSE_CORRECTANSWERS'
export const FETCH_OPTIONS_EXAMS_BY_COURSE_ID = 'FETCH_OPTIONS_EXAMS_BY_COURSE_ID'
export const NEXT_QUESTION_EXAM = 'NEXT_QUESTION_EXAM';
export const UNMOUNT_QUESTION_EXAM = 'UNMOUNT_QUESTION_EXAM'

